-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.playlists ADD created_by_name text;
-- ALTER TABLE public.playlists ADD created_by_avatar text;
